<?php
/**
 * @file
 * Hooks and helper functions for the cwrc_core_tweaks module.
 */

/* Hooks. */

/**
 * Implements hook_block_view_alter().
 */
function cwrc_core_tweaks_block_view_alter(&$data, $block) {
  if ($block->module === 'user' && $block->delta === 'online') {
    // Count users active within the defined period.
    $interval = REQUEST_TIME - variable_get('user_block_seconds_online', 900);

    // Perform database queries to gather online user lists. We use s.timestamp
    // rather than u.access because it is much faster.
    $authenticated_count = db_query("SELECT COUNT(DISTINCT s.uid) FROM {sessions} s WHERE s.timestamp >= :timestamp AND s.uid > 0", array(':timestamp' => $interval))->fetchField();

    // Append the badge to the subject.
    $data['subject'] .= ' <span class="badge">' . $authenticated_count . '</span>';
  }
}

/**
 * Implements hook_mail_alter().
 */
function cwrc_core_tweaks_mail_alter(&$message) {
  if ($message['id'] === 'user_register_pending_approval_admin') {
    // Define a new message body.
    $body = t("[user:name] has applied for an account, with the following reason:

***
[user:field-user-registration-reason]
***

[user:edit-url]", array(), array('langcode' => $message['language']->language));

    // Replace the tokens in the message body.
    $message['body'][0] = token_replace($body, array('user' => $message['params']['account']), array(
      'language' => $message['language'],
      'sanitize' => FALSE,
      'clear' => TRUE,
    ));
  }
}

/**
 * Implements hook_menu_breadcrumb_alter().
 */
function cwrc_core_tweaks_menu_breadcrumb_alter(&$active_trail, $item) {
  // Change the title of breadcrumb items linking to the front page from "Home"
  // to "CWRC" to avoid confusion with project homepages.
  // We must check that there _are_ breadcrumbs first, as the front page notably
  // does not display them.
  if (!empty($active_trail)) {
    foreach ($active_trail as &$breadcrumb) {
      if ($breadcrumb['href'] === '<front>') {
        $breadcrumb['title'] = t('CWRC');
      }
    }
  }
}
